<font color="teal">Broadcasting in Numpy</font>

In [ ]:
import numpy as np

X = np.array([
    [1,2,3],
    [2,3,4],
    [3,4,5],
    [4,5,6]
])
w = np.array([
    [10,20,30]
])
#Matrix X, vector w
X,w
# now add ea. vector w, to ea. row of X

for row in range(X.shape[0]):
    print(X[row]) #Before
    print(X[row] + w) #After adding vector w
#
## Review on slicing
A=[1,3,4]
A[-1] = [21]
A
B = list(range(1,10)) # create an array with values 1 thru 9
# B[lowerBound:UpperBound] upper non-inclusive
# B[start:stop:skip] this means something like B[::2] skip 2 for every element from 0 to the end
B[1:4]
B[::-1] # reverse a list

for row in range(X.shape[0]):
    # every sub array in Matrix X will b that subarray plus the vector 'w'
    X[row,:] = X[row,:] + w # The i'eth row , all columns

X
# or we can save off X by using an new matrix
import copy
Y = copy.deepcopy(X)
# y = np.zeros(X.shape)
for i in range(X.shape[0]):
    Y[i,:] = X[i,:] + w
Y

[1 2 3]
[[11 22 33]]
[2 3 4]
[[12 23 34]]
[3 4 5]
[[13 24 35]]
[4 5 6]
[[14 25 36]]


array([[21, 42, 63],
       [22, 43, 64],
       [23, 44, 65],
       [24, 45, 66]])

In [29]:
# Now the broadcasting way
# not valid in linear algebra terms because sizes do NOT match. Python w/analyze the sizes and determine that sizes match
# for row addition...same would be true if multiplication etc..
c = [50,40,30]
Z = X+c
print(Z), print(' ')
print(X)

[[61 62 63]
 [62 63 64]
 [63 64 65]
 [64 65 66]]
 
[[11 22 33]
 [12 23 34]
 [13 24 35]
 [14 25 36]]


In [38]:
# so the above was for rows, let's see about column-wise operations
v = np.array([-1,0,1,0]) # still dimensionless.. we need to tell it its a col vector
# 2 ways to do:
r = np.array([[-1],[0],[1],[0]])  # make every el it's own array
# or
s = np.array([-1,0,1,0],ndmin=2) # ndmin means minimum dimensions equals 2
s,s.T
X,X*s.T

(array([[11, 22, 33],
        [12, 23, 34],
        [13, 24, 35],
        [14, 25, 36]]),
 array([[-11, -22, -33],
        [  0,   0,   0],
        [ 13,  24,  35],
        [  0,   0,   0]]))

In [ ]:
# Ex:
import numpy as np
# 1) Create a vector of integers 0:8 (v)
# 2) reshape v into a 3x3 matrix (M) (np.reshape)
# 3) repeat M into a 9x3 (C) (np.tile)
# 4) broadcast-multiple C with v (B)
# 1
v = list(range(0,9)) # or could have done v = np.arange(9)
# 2
M = np.reshape(v,(3,3))
# 3
C = np.tile(M,(3,1))

# 4
# B = C*v # produces an error cause python wants to do broadcast  row-wise
# note np.reshape(v,(-1,1)) the -1 means the max length this should be

B = C*np.reshape(v,(len(v),1)) # tuple (9,1)
B,C
v,np.reshape(v,(len(v),1)),C
B

array([[ 0,  0,  0],
       [ 3,  4,  5],
       [12, 14, 16],
       [ 0,  3,  6],
       [12, 16, 20],
       [30, 35, 40],
       [ 0,  6, 12],
       [21, 28, 35],
       [48, 56, 64]])