<font color="teal" size=9>if else statements</font>

In [1]:
if True:
    print('this is true')


this is true


In [25]:
import numpy as np
r = np.random.randn()

if r>0:
    print('r greater than 0')
if r<0:
    print('r less than 0')
# or better form
if r>0:
    print('greater than 0')
else:
    print("less than")
# even better
if r>0:
    outcome = 'positive'
else:
    outcome = 'negative'
print("outcome " + outcome)

r greater than 0
greater than 0
outcome positive


In [28]:
caketype='carrot'
if caketype == 'carrot':
    print('love carrot')
elif caketype == 'choclate':
    print('love choco')
else:
    print("no cake to like")

love carrot


In [29]:
if caketype[0] == 'c': print('probably carrot')

probably carrot


In [33]:
print('carrot ck') if caketype[0].lower() == 'c' else print('dunn0o')

carrot ck


In [34]:
# conjunctive conditionals
if 1<3 and 4==5:
    print("both conditions are true")
else:
    print("At least one is true")

At least one is true


In [48]:
# Ex: Create a fcn that coputes the "dot product"
# e.g. [1,2,3]
#      [0,4,1]   two vectors w/same shape
# 1*0 + 2*4 + 3*1 = 8 + 3 = 11
# 1) check the boht inputs are numpy arrays (isinstance())
# 2) check taht the two inputs are the same length
# 3a) break out of fcn and give helpful error message. raise Exception()
# 3b) compute and return the dot product

A=np.array([1,2,3])
B=np.array([0,4,1])
C=np.dot(A,B)
# or
D=sum(A*B)
print("C " + str(C))
print("D is same as C " + str(D))
def dot_product(a,b):

    # if isinstance(a,numpy):
    # else:
    #     raise Exception('Wrong type')
    # if isinstance(b,numpy):
        
    # else:
    #     raise Exception('Wrong type')

    for i in range(len(a)):
        if not (isinstance(a,np.ndarray) and isinstance(b,np.ndarray)):
            raise Exception('Must be numpy arrays')
        if not len(a) == len(b):
            raise Exception('Must be same size')
        return sum(a*b)

res=dot_product(A,B)
print("Result " +str(res))
    

C 11
D is same as C 11
Result 11


<font color="teal" size=10> For loops</font>

In [49]:
for i in range(6):
    print(i)

0
1
2
3
4
5


In [50]:
for i in range(3,8):
    print(i)

3
4
5
6
7


In [54]:
import numpy as np
numbers = np.linspace(3,17.1,22)

for i in range(len(numbers)):
    x = numbers[i]
    print('Iteration ' + str(i) + ' has a value of ' + str(x))

Iteration 0 has a value of 3.0
Iteration 1 has a value of 3.6714285714285717
Iteration 2 has a value of 4.342857142857143
Iteration 3 has a value of 5.014285714285714
Iteration 4 has a value of 5.685714285714286
Iteration 5 has a value of 6.357142857142858
Iteration 6 has a value of 7.0285714285714285
Iteration 7 has a value of 7.7
Iteration 8 has a value of 8.371428571428572
Iteration 9 has a value of 9.042857142857144
Iteration 10 has a value of 9.714285714285715
Iteration 11 has a value of 10.385714285714286
Iteration 12 has a value of 11.057142857142857
Iteration 13 has a value of 11.72857142857143
Iteration 14 has a value of 12.4
Iteration 15 has a value of 13.071428571428573
Iteration 16 has a value of 13.742857142857144
Iteration 17 has a value of 14.414285714285715
Iteration 18 has a value of 15.085714285714287
Iteration 19 has a value of 15.757142857142858
Iteration 20 has a value of 16.42857142857143
Iteration 21 has a value of 17.1


In [57]:
# embed multiple flow-control statements
# odd numbers have modulus of 1
# even numbers have a modulus of 0
for n in range(18):
    if n%2 == 0:
        print('N is even ' +str(n))
    else:
        print('N is odd ' + str(n))

N is even 0
N is odd 1
N is even 2
N is odd 3
N is even 4
N is odd 5
N is even 6
N is odd 7
N is even 8
N is odd 9
N is even 10
N is odd 11
N is even 12
N is odd 13
N is even 14
N is odd 15
N is even 16
N is odd 17


In [128]:
# Exercise: Fibonacci series: [0,1,1,2,3,5,8,13]

def fibo(n):
    tot = 0
    tmp = [0,1,1]

    for i in range(1,n):
       # tmp.append(tmp[i]+1)
       # print('i ' + str(i)+ ' last ' + str(tmp[len(tmp)-1]))
        last = len(tmp)-1
        last2 = len(tmp)-2
        fib =  tmp[last] + tmp[last2]
        tmp.append(fib)    

    print("Tot: " + str(tmp[len(tmp)-1]))
    print(tmp)

# Udemy version
def fibseq(N):
    v = [0,1,1]
    for i in range(N-2):
        # add the last 2 elements
        v.append( sum(v[-2:]) )
    print(v)
fibo(6)
fibseq(6)
# print('udem ver' + str(x))

Tot: 13
[0, 1, 1, 2, 3, 5, 8, 13]
[0, 1, 1, 2, 3, 5, 8]


<font color="teal" size=9> Enumerate and Zip </font>



In [ ]:
import numpy as np

ns = np.linspace(-5,5,7)

for i in range(len(ns)):
    print('Index ' + str(i) + ' has a value of ' + str(ns[i]))


Index 0 has a value of -5.0
Index 1 has a value of -3.333333333333333
Index 2 has a value of -1.6666666666666665
Index 3 has a value of 0.0
Index 4 has a value of 1.666666666666667
Index 5 has a value of 3.333333333333334
Index 6 has a value of 5.0


In [ ]:
for i,n in enumerate(ns):
    # n = ns[i] does this for us
    print('Index ' + str(i) + ' has a value of ' + str(n))


Index 0 has a value of -5.0
Index 1 has a value of -3.333333333333333
Index 2 has a value of -1.6666666666666665
Index 3 has a value of 0.0
Index 4 has a value of 1.666666666666667
Index 5 has a value of 3.333333333333334
Index 6 has a value of 5.0


In [144]:
text = 'Hello my name is Mike.'

vowels = np.zeros(len(text))

#for i,l in enumerate(text):
   #\
   #  print(i,l)
#print(vowels)
# same as
print('old way')
# for i in range(len(text)):
#     l = text[i]
#     print(i,l)

for i,l in enumerate(text):
    if l in 'aeiou':
        vowels[i] = 1

vowels

old way


array([0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0.,
       0., 1., 0., 1., 0.])

In [ ]:
# what if u have two vectors not just 1 like the above in the text vector
listA = [3,4,5,6,3,-17]
listB = ['q','w','e','r','t','y']

for i in range(len(listA)):
    print('list A ' + str(listA[i]) + ' list B ' + str(listB[i]))

print('zip style ')

# if listA and listB are of diff lengths, zip will use the length of the shortest
for a,b in zip(listA,listB):
    print('list A ' + str(a) + ' list B ' + str(b))

list A 3 list B q
list A 4 list B w
list A 5 list B e
list A 6 list B r
list A 3 list B t
list A -17 list B y
zip style 
list A 3 list B q
list A 4 list B w
list A 5 list B e
list A 6 list B r
list A 3 list B t
list A -17 list B y


In [152]:
#Ex: Given the following lists, create a dictionary using zip
names = ['alpha','beata','gamma']
values=[10,20,30]
Book = dict()
for n,v in zip(names,values):
    Book[n]=v

print(Book)
# Udemy
Book2 = dict(zip(names,values))
Book2

{'alpha': 10, 'beata': 20, 'gamma': 30}


{'alpha': 10, 'beata': 20, 'gamma': 30}

In [154]:
# continue keyword

text = 'HellO, my name is MikE'

for i in text: # note we didn't use range(len(text)) cause we don't need i to be a number
    if i.lower() in 'aeiou':
        continue
    print(i)

H
l
l
,
 
m
y
 
n
m
 
s
 
M
k


In [ ]:
# initalizing
# need to initiaze before u use in a loop other because an empty array has no index

r = np.zeros(10)
r
# or
p = np.full(10,0)
p
# 
del r  # delete the variable r out of the python buffer workspace

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [ ]:
import numpy as np
# now what isn't too cool is the fact that you can make a 4x5 matrix w/random like so
m1 = np.random.randn(4,5)   # 4 rows, 5 columns
#m2 = np.zeros(4,5)  # will NOT do the same and make 4 rows and 5 columns! grr but we can add a tuple to do it
m3 = np.zeros((4,5))
m3
## 3 different ways of initializing
N=3
first = np.zeros(N)
second = np.array([]) #second.append(val)
third = [] # third.append(val)

# for i in range(N):
#     first = np.append(first,i) # already has 0s though
print(first)
for i in range(N):
    second = np.append(second,i)
for i in range(N):
    third.append(i)

third

[0. 0. 0. 0. 1. 2.]


[0, 1, 2]

In [191]:
# Compare  methods of array initializing
import time

N = 10000
toc = [0]*3 # array of 3 elements init by 0

# list method
first = []
tic = time.perf_counter()
for i in range(N):
    first.append(i**2)
toc[0] = (time.perf_counter() - tic)*1000 # miliseconds

# numpy append method
third = np.array([])
tic = time.perf_counter()
for i in range(N):
    third = np.append(third,i**2)
toc[1] = (time.perf_counter() - tic)*1000

# numpy init method
second = np.zeros(N)
tic = time.perf_counter()
for i in range(N):
    second[i]=i**2
toc[2] = (time.perf_counter() - tic)*1000 # milisconds
print('Lapsed time for np zero ' + str(toc))
#


Lapsed time for np zero [1.4216999989002943, 183.98149986751378, 3.579100128263235]


In [216]:
# List comprehension
import random
r = random.randint(1,10)
[ i**2 for i in range(r) if i > 5]
N = 10
a = [ i**2 for i in range(N)]

n1 = ['odd' if i %2 == 1 else i for i in range(N)]

n2 = [i**2 for i in range(N) if i > 5]

x1 = np.linspace(-3,3,1)
y1 = x1 * 2
x1,y1


(array([-3.]), array([-6.]))

In [2]:
# while loop
toggle = True
i = 0

while toggle:
    print(i)
    i += 1

    if (i == 8):
        toggle=False
j = 0
while j < 3:
    print('J ' + str(j))
    j += 1

0
1
2
3
4
5
6
7
J 0
J 1
J 2


In [ ]:
# Exercise: Poisson counter. Note a poisson counter is used to simulate the random firing of brain cells by counting
# the number of times it takes to go from 1 to some target value
# to create a poison counter
# 1) Specifiy a target: exp(-lambda) i.e. e^-lambda and we'll make lambda = 10
# 2) initalize a counter = 0, currval = 1
# 3) Multiply currval by a randon number U[0,1] i.e a Uniform Distribution
# 4) Repeat Step 3 until currval < target
# 5) return # fo times that you go through step 4
import numpy as np

def poissonCounter(lam):
    counter,currval = 0,1
    target = np.exp(-lam)

    while currval > target:
        counter += 1
        # rand() is the uniform dist
        currval *= np.random.rand()

    return counter

poissonCounter(10)

5

In [ ]:
import numpy as np

X = np.array([ [1,2,3],
              [2,3,4],
              [3,4,5],
              [4,5,6]
            ])
w = np.array([10,20,30])
print(X),print(' ')
print(w)
# X.shape --> (4,3)

for i in range(X.shape[0]):
    X[i,:] = X[i,:] + w

# Note if you didn't want to overwrite X an thus preserve it you can Save it to a new var but first copy
# Y = copy.deepcopy(X) or just init with zeros Y = np.zeros(X.shape)


[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]
 
[10 20 30]


array([[11, 22, 33],
       [12, 23, 34],
       [13, 24, 35],
       [14, 25, 36]])